
server:
  port: 9098

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_service?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


logging:
  pattern:
    file: "%d [%level] %c{1.} [%t] %m%n"
  file:
    path: /logs/
    name: student_service.log